### ISSUE TITLE
Enable flag to merge instead of patch thanos.spec.storeGateway.containerOverrides.volumeMounts

### ISSUE THREAD

**Issue by NissesSenap** [banzaicloud/thanos-operator#109]
**Is your feature request related to a problem? Please describe.**

When setting a custom data store in thanos.spec.storeGateway.containerOverrides.volumeMounts the objectstore configmap get's overwritten.
This kind of destroys the usability of having ObjectStore.

**Describe the solution you'd like to see**

Add bool merge under thanos.spec.storeGateway.containerOverrides.volumeMounts or set merge/patch as default.

Example

```yaml
apiVersion: monitoring.banzaicloud.io/v1alpha1
kind: Thanos
metadata:
  name: thanos-sample
spec:
  queryDiscovery: true
  query: {}
  storeGateway:
    containerOverrides:
      volumeMounts:
        - name: thanos-data
          mountPath: ./data
          merge: true
        - mountPath: /etc/config/
          name: objectstore-secret
          readOnly: true
    workloadOverrides:
      volumes:
        - name: thanos-data
          emptyDir: {}
        - name: objectstore-secret
          secret:
            defaultMode: 420
            secretName: thanos-objstore-config
```

**Describe alternatives you've considered**

Ether make merge/path to the default or make it opt in or opt out.

**Additional context**

I need to define a location to store my volumeMounts due to that I have PSP rules that say I'm not allowed to write data to root dir.
