### ISSUE TITLE
Wrong discovery domains created when queryDiscovery is set to true

### ISSUE THREAD

**Issue by maZahaca** [banzaicloud/thanos-operator#111]
**Describe the bug**
I followed [this blog post](https://banzaicloud.com/blog/thanos-operator/#observer-cluster-deployment) to setup the thanos observer/observee clusters.

When I apply following resource it creates wrong discovery domains:
```
apiVersion: monitoring.banzaicloud.io/v1alpha1
kind: Thanos
metadata:
  name: query-master
spec:
  query: {}
  queryDiscovery: true
```

Created result:
```
apiVersion: apps/v1
kind: Deployment
spec:
  template:
    spec:
      containers:
        - args:
            - query
            - --grpc-address=0.0.0.0:10901
            - --http-address=0.0.0.0:10902
            - --log.level=info
            - --store=dnssrvnoa+_grpc._tcp.thanos-apps-query.monitoring.cluster.local.cluster.local
            - --store=dnssrvnoa+_grpc._tcp.thanos-monitoring-query.monitoring.cluster.local.cluster.local
            - --store=dnssrvnoa+_grpc._tcp.thanos-data-query.monitoring.cluster.local.cluster.local
          image: quay.io/thanos/thanos:v0.15.0
```

Take a look into this part `cluster.local.cluster.local`

**Steps to reproduce the issue:**
1. install operator
```
helm install thanos-operator --namespace monitor banzaicloud-stable/thanos-operator --set manageCrds=false
```
Installed chart version: 0.1.1

2. apply resources from the articles observer/observee -> https://banzaicloud.com/blog/thanos-operator/#observer-cluster-deployment
3. `kubectl get deploy thanos-query-master-query -o yaml` find wrong descriptions of discovery domains 

**Expected behavior**
This part:
```
            - --store=dnssrvnoa+_grpc._tcp.thanos-apps-query.monitoring.cluster.local.cluster.local
            - --store=dnssrvnoa+_grpc._tcp.thanos-monitoring-query.monitoring.cluster.local.cluster.local
            - --store=dnssrvnoa+_grpc._tcp.thanos-data-query.monitoring.cluster.local.cluster.local
```
Should looks like this:
```
            - --store=dnssrvnoa+_grpc._tcp.thanos-apps-query.monitoring.cluster.local
            - --store=dnssrvnoa+_grpc._tcp.thanos-monitoring-query.monitoring.cluster.local
            - --store=dnssrvnoa+_grpc._tcp.thanos-data-query.monitoring.cluster.local
```
