### ISSUE TITLE
Some arguments are missing from generation

### ISSUE THREAD

**Issue by hanjunlee** [banzaicloud/thanos-operator#189]
**Describe the bug**
The operator does not generate some arguments from the custom resources. In particular, the arguments that type is `int` and `*bool` are not created.

**Steps to reproduce the issue:**
1) Apply the Thanos resource like the one below to a cluster that has the Thanos operator.

```yaml
apiVersion: monitoring.banzaicloud.io/v1alpha1
kind: Thanos
metadata:
  name: thanos
  namespace: metrics
spec:
  query:
    queryReplicaLabel: ["prometheus", "prometheus_replica"]
  queryFrontend: 
    queryRangeSplit: 30m
    queryFrontendCompressResponses: true
    queryRangePartialResponse: true
    queryRangeMaxRetriesPerRequest: 1
  queryDiscovery: true
```

2) Describe the `thanos-query-front` Deployment; you can figure out the `args` field misses some arguments like the one below. 

```yaml
  Containers:
   query-frontend:
    Image:      quay.io/thanos/thanos:v0.22.0
    Port:       9090/TCP
    Host Port:  0/TCP
    Args:
      query-frontend
      --http-address=0.0.0.0:9090
      --log.level=debug
      --query-frontend.downstream-url=http://thanos-query.metrics.svc.cluster.local:10902
      --query-range.split-interval=30m
```

**Expected behavior**
The `thanos-query-front` Deployment should have the arguments - `--query-range.partial-response` and `--query-range.max-retries-per-request=1` - under the `args` field.

**Additional context**
* Thanos operator version: `0.3.7`
