### ISSUE TITLE
Allow extraArgs on the Thanos CR

### ISSUE THREAD

**Issue by achetronic** [banzaicloud/thanos-operator#207]
**Is your feature request related to a problem? Please describe.**

currently on Thanos CR to enable GRPC client TLS secure we need to ad some extra flag. The problem is that deploymentoverrides forces you to override all the flags, colliding with the rest of CR

```yaml
        query:

          stores:
             - "thanos-sidecar-p2.monitoring.your-domain.io:443"
          deploymentOverrides:
            spec:
              template:
                spec:
                  containers:
                    - name: query
                      args:
                        - query
                        - --grpc-address=0.0.0.0:10901
                        - --http-address=0.0.0.0:10902
                        - --store=thanos-sidecar-p2.monitoring.your-domain.io:443
                        - --grpc-client-tls-secure
```

As you can see in the previous piece, if you need to set `--grpc-client-tls-secure` you need to write again the rest of the flags

**Describe the solution you'd like to see**

```yaml
        query:
          stores:
             - thanos-sidecar-p2.monitoring.your-domain.io:443
          extraArgs:
            - --grpc-client-tls-secure
```

**Describe alternatives you've considered**

There is no alternative due to, if you point your Thanos Query to external sidecars, you should use at least TLS. If you don't set this flag on the args, Thanos Query simply fails because of `connection closed` errors

**Additional context**

@Matthew-Beckett Ping you here because you are the latest active on the repo :)
