### ISSUE TITLE
Thanos 0.13.0 bucket web has changed arguments

### ISSUE THREAD

**Issue by ekarlso** [banzaicloud/thanos-operator#35]
**Is your feature request related to a problem? Please describe.**

Thanos operator is spwaning bucket web with wrong args for 0.13+

```
 containers:
  - args:
    - bucket
    - web
    - --log.level=info
    - --http-address=0.0.0.0:10902
    - --objstore.config-file=/etc/config/object-store.yaml
    - --refresh=1800s
    - --timeout=300s
    image: quay.io/thanos/thanos:v0.13.0
    imagePullPolicy: Always
    name: bucket
    ports:
    - containerPort: 10902
      name: http
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
```

**Describe the solution you'd like to see**

Change arguments for the deployment to use correct args aka
```tools bucket web``` instead of current

**Additional context**

I got a PR coming up after I have tested it.
