### ISSUE TITLE
Ingress Annotations

### ISSUE THREAD

**Issue by Sadzeih** [banzaicloud/thanos-operator#41]
**Is your feature request related to a problem? Please describe.**

I want to be able to annotate the ingress to let cert-manager and nginx handle the certs etc...

**Describe the solution you'd like to see**

I'd love to have the ability to do:

```yaml
HTTPIngress:
  host: query.example.com
  path: /
  annotations:
    "kubernetes.io/ingress.class": nginx
    "cert-manager.io/cluster-issuer": "letsencrypt-prod"
    "kubernetes.io/tls-acme": "true"
```
