### ISSUE TITLE
Too many colons in StoreEndpoint url

### ISSUE THREAD

**Issue by Sadzeih** [banzaicloud/thanos-operator#42]
**Describe the bug**

When I configure a `StoreEndpoint` like this:

```yaml
apiVersion: monitoring.banzaicloud.io/v1alpha1
kind: StoreEndpoint
metadata:
  name: storeendpoint-mwm-shop-cluster
spec:
  thanos: thanos
  url: https://url.to.my.external.querier:443
  config:
    mountFrom:
      secretKeyRef:
        name: thanos-storage-config
        key: config
```
I get this error:

```
fetching store info from https://url.to.my.external.querier:443: rpc error: code = DeadlineExceeded desc = latest connection error: connection error: desc = "transport: Error while dialing dial tcp: address https://url.to.my.external.querier:443: too many colons in address" 
```

**Steps to reproduce the issue:**

N/A

**Expected behavior**

I should have my querier correctly connected

**Screenshots**

N/A

**Additional context**

Installed from the helm chart
