### ISSUE TITLE
make image repository configurable

### ISSUE THREAD

**Issue by kperlaska** [banzaicloud/thanos-operator#46]
**Is your feature request related to a problem? Please describe.**
since the image repository is hardcoded here we cannot deploy this on an airgapped cluster:
https://github.com/banzaicloud/thanos-operator/blob/master/pkg/sdk/api/v1alpha1/thanos_types.go#L23

**Describe the solution you'd like to see**
make the imagepath (and maybe the the tag) configurable.

**Describe alternatives you've considered**
There is no real alternative for this.

**Additional context**

**Comment by Ultrafenrir** [comment]
+1 will be very cool to configure image tag as well (at least provide a choice between compatible versions)

**Comment by Ultrafenrir** [comment]
i've managed to setup custom images with the following config

```
apiVersion: monitoring.banzaicloud.io/v1alpha1
kind: Thanos
metadata:
  name: thanos
spec:
  rule:
    containerOverrides:
      image: registry/thanos:0.16.0

```

But referring to the CRD's spec:

```
                image:
                  properties:
                    pullPolicy:
                      description: PullPolicy describes a policy for if/when to pull
                        a container image
                      type: string
                    repository:
                      type: string
                    tag:
                      type: string
                  type: object
```

Operator should support the following config:

```
apiVersion: monitoring.banzaicloud.io/v1alpha1
kind: ObjectStore
metadata:
  name: sample
spec:
  config:
    mountFrom:
      secretKeyRef:
        name: sample
        key: object-store.yaml
  compactor:
    containerOverrides:
      image:
        repository: registry/thanos
        tag: 0.16.0 
```

But it is failing on resource creation with following error:

`E1026 05:32:11.646544 1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.6/tools/cache/reflector.go:125: Failed to list *v1alpha1.ObjectStore: v1alpha1.ObjectStoreList.Items: []v1alpha1.ObjectStore: v1alpha1.ObjectStore.Spec: v1alpha1.ObjectStoreSpec.Compactor: v1alpha1.Compactor.ContainerOverrides: types.ContainerBase.Image: ReadString: expects " or n, but found {, error found in #10 byte of ...|{"image":{"repositor|..., bigger context ...|pec":{"compactor":{"containerOverrides":{"image":{"repository":"registry/thanos","t|...`


Looks like it's a bug @tarokkk
