### ISSUE TITLE
Absence of store endpoints in query with sample configuration

### ISSUE THREAD

**Issue by Ultrafenrir** [banzaicloud/thanos-operator#56]
**Describe the bug**
No store endpoints registered in query after single cluster setup on version 0.1.1

**Steps to reproduce the issue:**

sample Configuration from here https://banzaicloud.com/blog/thanos-operator/#single-cluster-deployment

**some secret here**

```
apiVersion: monitoring.banzaicloud.io/v1alpha1
kind: ObjectStore
metadata:
  name: objectstore-sample
spec:
  config:
    mountFrom:
      secretKeyRef:
        name: some-secret 
        key: object-store.yaml
  compactor: {}


apiVersion: monitoring.banzaicloud.io/v1alpha1
kind: StoreEndpoint
metadata:
  name: storeendpoint-sample
spec:
  thanos: thanos-sample
  config:
    mountFrom:
      secretKeyRef:
        name: some-secret
        key: object-store.yaml
  selector: {}


apiVersion: monitoring.banzaicloud.io/v1alpha1
kind: Thanos
metadata:
  name: thanos-sample
spec:
  queryDiscovery: true
  clusterDomain: some-custom-name
  query: {}
  queryFrontend: {}
  storeGateway: {}

```
**Expected behavior**
After store-gateway creation it should automatically appear in query "stores"
