### ISSUE TITLE
Overriding meta replicas is not working

### ISSUE THREAD

**Issue by Ultrafenrir** [banzaicloud/thanos-operator#61]
**Describe the bug**
If u will try to setup the following config

```
apiVersion: monitoring.banzaicloud.io/v1alpha1
kind: Thanos
metadata:
  name: thanos
spec:
  clusterDomain: platform-rke-test-env
  enableRecreateWorkloadOnImmutableFieldChange: true
  query:
    metaOverrides:
      replicas: "3"
```

u still get only 1 pod of query

**Steps to reproduce the issue:**
Set the 
```
  query:
    metaOverrides:
      replicas: "3"
```
**Expected behavior**
U should be able to control the number of instances for query and queryFrontend 

**Additional context**
With query there are a strange behaviour ,  every time i deploy query even without

```
   query:
    metaOverrides:
      replicas: "3"

```

i getting 2 instances of query until one of them don't pass readiness probe, then the second one is marking as "removing"
And if i set replicas into 2 or 3 , i will get 3 instances of query on startup, but then 2 of them will be removed.

The same thing with queryFrontend
