### ISSUE TITLE
queryFrontend don't respect flags described in types

### ISSUE THREAD

**Issue by Ultrafenrir** [banzaicloud/thanos-operator#63]
**Describe the bug**
When i trying setup following configuration

```
  queryFrontend:
    queryRangeMaxRetriesPerRequest: 2
    queryRangeMaxQueryParallelism: 14  
    queryRangeSplit: "6h"
    queryRangeResponseCacheMaxFreshness: "5m"
```
operator don't add into deployment following  args   

```
--query-range.max-retries-per-request
--query-range.max-query-parallelism
```

**Steps to reproduce the issue:**
add into the configuration

```
    queryRangeMaxRetriesPerRequest: 
    queryRangeMaxQueryParallelism:  
``` 

**Expected behavior**

```
--query-range.max-retries-per-request
--query-range.max-query-parallelism
```
should be added to deployment args 

**Additional context**
Maybe related to the type, cause other option(string based) working just fine
