### ISSUE TITLE
store option "timeRanges" has no effect

### ISSUE THREAD

**Issue by craigfurman** [banzaicloud/thanos-operator#73]
**Describe the bug**

Setting `Thanos.spec.storeGateway.timeRanges`, as documented in https://github.com/banzaicloud/thanos-operator/blob/master/docs/types/thanos_types.md, has no effect.

**Steps to reproduce the issue:**

Upload the following manifests:

```
apiVersion: monitoring.banzaicloud.io/v1alpha1
kind: Thanos
metadata:
  name: thanos
spec:
  storeGateway:
    timeRanges:
    - maxTime: -24h
---
apiVersion: monitoring.banzaicloud.io/v1alpha1
kind: StoreEndpoint
metadata:
  name: bucket
spec:
  config:
    mountFrom:
      secretKeyRef:
        key: EXAMPLE
        name: EXAMPLE
  thanos: thanos
```

Observe that the resultant store pods do not have a `--max-time flag`

**Expected behavior**

I'd expect the resultant store pods' `Pod.spec.containers.args` to have a `--max-time=-24h` argument.

**Screenshots**

**Additional context**

It's possible I've misunderstood the operator code, but it looks like this option does nothing, looking at this [`setArgs`](https://github.com/banzaicloud/thanos-operator/blob/master/pkg/resources/store/store.go#L109) function. We either need to set the flags with reflection on a `thanos` struct tag, if this is not too awkward to do with the nested struct, or write code to handle this field.
