### ISSUE TITLE
Error setting query and store response timeouts

### ISSUE THREAD

**Issue by lanecm** [banzaicloud/thanos-operator#74]
**Describe the bug**

When trying to set:

```yaml
apiVersion: monitoring.banzaicloud.io/v1alpha1
kind: Thanos
metadata:
  name: thanos
  namespace: monitoring
spec:
  query:
    queryTimeout: 120s
    storeResponseTimeout: 120s
```

I get the following error from `thanos-query` pod:

```text
Error parsing commandline arguments: not a valid duration string: "&Duration{Duration:2m0s,}"
```

Seems like the string value based to `thanos query` is not right?

**Steps to reproduce the issue:**

Apply the above yaml for Thanos.

**Expected behavior**

Expected the query and store response timeouts to be set to 120s.

**Screenshots**

N/A

**Additional context**

Please let me know if you need additional information!
