### ISSUE TITLE
store: Implement hashmod sharding

### ISSUE THREAD

**Issue by SuperQ** [banzaicloud/thanos-operator#75]
**Is your feature request related to a problem? Please describe.**

To handle very large TSDB buckets, allow sharding with `hashmod`

**Describe the solution you'd like to see**

Specifying a replica count for stores will automatically generate a bucket relabel config that splits with `hashmod`.

```
      spec:
        containers:
        - args:
          - store
          - |
            --selector.relabel-config=
              - action: hashmod
                source_labels: ["__block_id"]
                target_label: shard
                modulus: 3
              - action: keep
                source_labels: ["shard"]
                regex: 0
```

**Describe alternatives you've considered**

Label or time range sharding is also an option, but IMO this setup would be easier to scale.

**Additional context**

For example, we have a bucket storage with 10k individual TSDB blocks coming from a dozen Prometheus instances. Rather than try to manually shard based on external lables, we can reasonably evenly divide the work among a number of replicas based on consistent hash of block ID.

See the Relabling docs: https://thanos.io/tip/thanos/sharding.md/#relabelling
